{{- $directory := printf "%s/*" .Values.nginx.configPath }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-ws.nginxconf" . }}
data:
{{ (.Files.Glob $directory).AsConfig | indent 2 }}
