{{- $directory := printf "%s/*" .Values.thronesdbPhp.configPath }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thronesdb-php.config" . }}
data:
{{ (.Files.Glob $directory).AsConfig | indent 2 }}
