apiVersion: v1
kind: Service
metadata:
  name: {{ include "thronesdb-php.fullname" . }}
  labels:
    {{- include "thronesdb-php.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: php
      protocol: TCP
      name: php
  selector:
    {{- include "thronesdb-php.selectorLabels" . | nindent 4 }}
