apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "throneteki-node.envVars" . }}
data:
  PORT: "{{ .Values.service.port }}"
  NODE_ENV: production
  SERVER: {{ include "throneteki-node.fullname" . }}
  NODE_PATH: "{{ .Values.thronetekiNode.node_path }}"
