apiVersion: v1
kind: Service
metadata:
  name: {{ include "throneteki-node.fullname" . }}
  labels:
    {{- include "throneteki-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "throneteki-node.selectorLabels" . | nindent 4 }}
